name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs once a day
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated to latest version
        
      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Jeevanandh32
          outputs: dist/snake.svg
          
      - name: Commit and Push Snake
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Generated contribution snake"
          git push
